# Generated by Django 4.2.5 on 2023-09-12 13:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_character_created_at_character_updated_at_and_more'),
        ('cast', '0002_person_created_at_person_updated_at_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reviews',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.character'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cast.person'),
        ),
    ]
