# Generated by Django 4.2.5 on 2023-09-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviews_created_at_reviews_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
