# Generated by Django 4.2.5 on 2023-09-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0002_person_created_at_person_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
