# Generated by Django 4.2.5 on 2023-09-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0003_alter_person_biography_alter_person_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
