# Generated by Django 4.2.5 on 2023-09-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_character_created_at_character_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
