# Generated by Django 4.2.5 on 2023-09-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_character_character_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
